#include "astc-codec/src/base/optional.h"
#include "astc-codec/src/decoder/footprint.cc"
#include "astc-codec/src/decoder/physical_astc_block.cc"
#include "astc-codec/src/decoder/integer_sequence_codec.cc"
#include "astc-codec/src/decoder/astc_file.cc"
#include "astc-codec/src/decoder/logical_astc_block.cc"
#include "astc-codec/src/decoder/intermediate_astc_block.cc"
#include "astc-codec/src/decoder/partition.cc"
#include "astc-codec/src/decoder/quantization.cc"
#include "astc-codec/src/decoder/weight_infill.cc"
#include "astc-codec/src/decoder/endpoint_codec.cc"
#include "astc-codec/src/decoder/codec.cc"

#include "image.cpp"
#include "image_gnf.cpp"
